In [79]:
from google.colab import files
uploaded = files.upload()


Saving dataset_melspectrogram.npy to dataset_melspectrogram.npy


In [0]:
import numpy as np
import pandas as pd

data = pd.DataFrame(np.load("dataset_melspectrogram.npy",allow_pickle= True))
data.columns = ['feature', 'label']

from sklearn.preprocessing import LabelEncoder

X = np.array(data.feature.tolist())
y = np.array(data.label.tolist())
from sklearn.model_selection import train_test_split
X,val_x,y,val_y = train_test_split(X,y)
lb = LabelEncoder()

from keras.utils import np_utils

y = np_utils.to_categorical(lb.fit_transform(y))
val_y = np_utils.to_categorical(lb.fit_transform(val_y))

In [0]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adam
from keras.utils import np_utils
from sklearn import metrics 



num_labels = y.shape[1]
filter_size = 2




# build model
model = Sequential()


model.add(Dense(512, input_shape=(128,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))


model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))


model.add(Dense(num_labels))
model.add(Activation('softmax'))



model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [181]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_28 (Dense)             (None, 512)               66048     
_________________________________________________________________
activation_28 (Activation)   (None, 512)               0         
_________________________________________________________________
dropout_19 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_29 (Dense)             (None, 256)               131328    
_________________________________________________________________
activation_29 (Activation)   (None, 256)               0         
_________________________________________________________________
dropout_20 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_30 (Dense)             (None, 10)                2570      
__________

In [183]:
model.fit(X, y, batch_size=64, epochs=72, validation_data=(val_x, val_y))

Train on 6549 samples, validate on 2183 samples
Epoch 1/72
6549/6549 [==============================] - 0s 67us/step - loss: 0.7896 - acc: 0.7540 - val_loss: 0.8349 - val_acc: 0.7604
Epoch 2/72
6549/6549 [==============================] - 0s 62us/step - loss: 0.7903 - acc: 0.7528 - val_loss: 0.8169 - val_acc: 0.7645
Epoch 3/72
6549/6549 [==============================] - 0s 61us/step - loss: 0.7718 - acc: 0.7619 - val_loss: 0.8085 - val_acc: 0.7609
Epoch 4/72
6549/6549 [==============================] - 0s 59us/step - loss: 0.8004 - acc: 0.7577 - val_loss: 0.7944 - val_acc: 0.7687
Epoch 5/72
6549/6549 [==============================] - 0s 60us/step - loss: 0.7847 - acc: 0.7569 - val_loss: 0.8322 - val_acc: 0.7563
Epoch 6/72
6549/6549 [==============================] - 0s 64us/step - loss: 0.8044 - acc: 0.7528 - val_loss: 0.8074 - val_acc: 0.7673
Epoch 7/72
6549/6549 [==============================] - 0s 62us/step - loss: 0.7767 - acc: 0.7557 - val_loss: 0.8146 - val_acc: 0.7705
Epoch 8

##### Real voice for Example

In [0]:
t = np.array(([[1.15493136e+00, 2.10298052e-01, 1.05901701e-01, 1.03373285e-01,
       1.59867378e-01, 1.12249504e-01, 1.36739965e-01, 9.98120482e-02,
       1.15319728e-01, 9.83339840e-02, 9.16686853e-02, 1.19656299e-01,
       1.59758105e-01, 1.67325443e-01, 1.86402600e-01, 2.12975184e-01,
       2.31010683e-01, 2.63181930e-01, 2.63148158e-01, 2.84946574e-01,
       2.28883849e-01, 2.68223562e-01, 3.30641298e-01, 3.08460060e-01,
       3.13056225e-01, 2.73003325e-01, 2.42380935e-01, 2.24883289e-01,
       1.94566200e-01, 2.00358464e-01, 2.16113828e-01, 2.80035372e-01,
       3.39006161e-01, 4.92212008e-01, 3.48604073e-01, 1.71719988e-01,
       1.64796059e-01, 1.79469613e-01, 1.47117126e-01, 1.74012518e-01,
       1.92526171e-01, 1.70098030e-01, 1.39364421e-01, 1.42388308e-01,
       1.59197231e-01, 1.20166959e-01, 1.12824481e-01, 1.17615444e-01,
       9.99552547e-02, 9.03600785e-02, 6.95672167e-02, 6.35501180e-02,
       5.11677198e-02, 5.41690983e-02, 6.01481503e-02, 5.97929026e-02,
       5.27991220e-02, 4.97274766e-02, 4.86544909e-02, 4.94390188e-02,
       4.41017216e-02, 3.95325518e-02, 4.01408952e-02, 4.07945929e-02,
       4.36251268e-02, 5.77484790e-02, 5.23161590e-02, 5.30011481e-02,
       4.48174342e-02, 5.74205155e-02, 5.16235435e-02, 2.70089011e-02,
       2.17748558e-02, 2.35853489e-02, 1.80708654e-02, 1.49908225e-02,
       1.39364564e-02, 1.13363997e-02, 1.12072589e-02, 1.30633108e-02,
       1.23835278e-02, 1.18411097e-02, 1.18238301e-02, 1.05835251e-02,
       1.24288570e-02, 1.24108279e-02, 1.13383377e-02, 1.17887514e-02,
       1.13309365e-02, 1.08556195e-02, 9.51523169e-03, 8.61057111e-03,
       8.59713014e-03, 9.11368410e-03, 8.91576623e-03, 8.43364419e-03,
       6.84650706e-03, 6.28971977e-03, 5.31512221e-03, 4.56287185e-03,
       4.01436960e-03, 3.76829297e-03, 3.06528732e-03, 2.70297262e-03,
       2.35203755e-03, 2.08847257e-03, 1.84738122e-03, 1.66534314e-03,
       1.51928040e-03, 1.45878618e-03, 1.34530812e-03, 1.29033217e-03,
       1.25068392e-03, 1.28685984e-03, 1.32355408e-03, 1.29465312e-03,
       1.27020425e-03, 1.22639119e-03, 1.13234835e-03, 9.30905191e-04,
       7.25273156e-04, 5.30564969e-04, 3.27436367e-04, 1.60595047e-04,
       5.77387158e-05, 1.52281969e-05, 2.61043829e-06, 2.46439030e-07]]))

###### it predicted right a real world sound
http://soundbible.com/460-Children-Playing.html

In [204]:
pred = model.predict_classes(t)
pred

array([2])

**Implementing XGBOOST Algorithm**

In [0]:
train = np.argmax(y,axis =  1)

In [0]:
test = np.argmax(val_y,axis =  1)

In [207]:
x =X
X.shape


(6549, 128)

In [0]:
test_x = val_x

In [0]:
from xgboost import XGBClassifier

In [0]:
model = XGBClassifier(learning_rate =0.1, 
                      n_estimators=280, 
                      max_depth=5,
                      min_child_weight=1, 
                      gamma=0, 
                      subsample=0.8, 
                      colsample_bytree=0.8,
                      objective= 'binary:logistic', 
                      nthread=4, 
                      scale_pos_weight=1, 
                      seed=60)


In [211]:
model.fit(x,train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=None, n_estimators=280, n_jobs=1,
              nthread=4, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=60,
              silent=None, subsample=0.8, verbosity=1)

In [0]:
pred = model.predict(test_x)

In [213]:
test

array([3, 4, 2, ..., 8, 7, 0])

In [214]:
pred

array([3, 4, 2, ..., 8, 7, 0])

In [215]:
import sklearn.metrics as met
met.accuracy_score(test, pred)

0.8850206138341732

In [216]:
met.confusion_matrix(test, pred)

array([[237,   0,   3,   0,   1,   0,   0,   1,   0,   1],
       [  1,  84,   2,   5,   3,   0,   1,   1,   0,   7],
       [  2,   0, 226,   6,   8,   2,   1,   1,   2,  15],
       [  5,   1,  22, 213,   5,   0,   2,   1,  10,  15],
       [  1,   0,   7,   3, 220,   0,   0,   8,   1,   5],
       [  1,   1,   7,   0,   0, 245,   1,   0,   2,   1],
       [  1,   0,   6,   2,   6,   1,  73,   4,   0,   2],
       [  1,   0,   0,   0,   7,   0,   1, 217,   0,   3],
       [  0,   0,   5,   1,   0,   0,   0,   2, 221,   5],
       [  3,   1,  22,   6,   3,   0,   2,   3,   2, 196]])